name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'
  PHP_VERSION: '8.3'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        coverage: none
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: wp-content/themes/muve-theme/package-lock.json
    
    - name: Validate composer.json and composer.lock
      run: |
        if [ -f composer.json ]; then
          composer validate --strict
        fi
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Install theme dependencies
      working-directory: wp-content/themes/muve-theme
      run: |
        npm ci
        npm run production
    
    - name: Run theme build
      working-directory: wp-content/themes/muve-theme
      run: npm run build
    
    - name: PHP Syntax Check
      run: |
        find wp-content/themes/muve-theme -name "*.php" -exec php -l {} \;
    
    - name: Check file permissions
      run: |
        find . -type f -name "*.sh" -exec chmod +x {} \;
        
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Validate Docker Compose
      run: docker-compose config
    
    - name: Build Docker images
      run: docker-compose build --no-cache
    
    - name: Start containers
      run: |
        docker-compose up -d
        sleep 30  # Wait for services to be ready
    
    - name: Check WordPress health
      run: |
        curl -f http://localhost:8080 || exit 1
    
    - name: Stop containers
      if: always()
      run: docker-compose down
      
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
        
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        tools: phpcs, phpcbf
    
    - name: Run PHP CodeSniffer
      run: |
        if [ -d "wp-content/themes/muve-theme" ]; then
          phpcs --standard=WordPress wp-content/themes/muve-theme --extensions=php --ignore=node_modules,vendor,assets
        fi
      continue-on-error: true