name: Claude Auto-Merge

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_review' && 
      github.event.review.state == 'approved' &&
      contains(github.event.review.body, 'Claude Review Complete') &&
      contains(github.event.review.body, 'No issues found')
    
    steps:
      - name: Check PR details
        id: pr-check
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            // Check if PR has any of the exclusion labels
            const exclusionLabels = ['needs-discussion', 'security', 'breaking-change'];
            const prLabels = pr.labels.map(label => label.name);
            const hasExclusionLabel = exclusionLabels.some(label => prLabels.includes(label));
            
            if (hasExclusionLabel) {
              console.log('PR has exclusion label, skipping auto-merge');
              return { shouldMerge: false };
            }
            
            // Check if target branch is protected
            const protectedBranches = ['main', 'production'];
            if (protectedBranches.includes(pr.base.ref)) {
              console.log('Target branch is protected, skipping auto-merge');
              return { shouldMerge: false };
            }
            
            return { shouldMerge: true };
      
      - name: Wait for checks to complete
        if: steps.pr-check.outputs.shouldMerge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });
            
            const pending = checks.check_runs.filter(check => check.status !== 'completed');
            if (pending.length > 0) {
              console.log('Waiting for checks to complete...');
              await new Promise(resolve => setTimeout(resolve, 30000)); // Wait 30 seconds
            }
      
      - name: Auto-merge PR
        if: steps.pr-check.outputs.shouldMerge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                merge_method: 'squash',
                commit_title: `Auto-merge: ${context.payload.pull_request.title}`,
                commit_message: `${context.payload.pull_request.body}\n\nAuto-merged by Claude after successful review.`
              });
              
              console.log('PR successfully auto-merged!');
              
              // Delete branch if it's not from a fork
              if (!context.payload.pull_request.head.repo.fork) {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${context.payload.pull_request.head.ref}`
                });
                console.log('Branch deleted');
              }
              
              // Add comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: '✅ Auto-merged by Claude after successful review and all checks passing!'
              });
              
            } catch (error) {
              console.error('Failed to auto-merge:', error);
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `❌ Auto-merge failed: ${error.message}\n\nPlease merge manually.`
              });
            }